### ISSUE TITLE
Internal Compiler Error: TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by catalinaperalta** [microsoft/cadl#1043]
I have been working on a Form Recognizer CADL spec and encountered this error after updating imports.
```
Internal Compiler error
File issue at https://github.com/microsoft/cadl
TypeError: Converting circular structure to JSON --> starting at object with constructor 'Object' | property 'id' -> object with constructor 'Object' --- property 'parent' closes the circle at JSON.stringify (<anonymous>) at emitOpenAPIFromVersion (https://cadlplayground.z22.web.core.windows.net/libs/@cadl-lang/openapi3/index.js:324:50) at Object.emitOpenAPI (https://cadlplayground.z22.web.core.windows.net/libs/@cadl-lang/openapi3/index.js:296:19) at async Object.$onEmit [as emitter] (https://cadlplayground.z22.web.core.windows.net/libs/@cadl-lang/openapi3/index.js:139:5) at async createProgram (https://cadlplayground.z22.web.core.windows.net/libs/@cadl-lang/compiler/index.js:32003:9) at async Module.compile (https://cadlplayground.z22.web.core.windows.net/libs/@cadl-lang/compiler/index.js:32540:12) at async B (https://cadlplayground.z22.web.core.windows.net/assets/index.3c238f25.js:483:513)
```

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOw0K0xt2ZXJzaW9uaW5nxCENCnVzaW5nIENhZGwuSHR0cDvNElbJLcUsDQpAZG9jKCJFeHRyYWN0cyBjb250ZW50LCBsYXlvdXQsIGFuZCBzdHJ1Y3R1cmVkIGRhdGEgZnJvbSBkb2N1bWVudHMuIikNCkBzZXJ2aWNlVGl0bGUoIkZvcm0gUmVjb2duaXplciBDbGllbnTMKecAiShBUEnHC3MudjPIIWVyKCJodHRwczovL3tlbmRwb2ludH0vZm9ybXLJViIsICJSZWdpb25hbCDIJSIsIHsNCiAg5gDY8ACIcmVzb3VyY2XKLynELcgOOuQA62luZywNCn0p5QEe5wFdZWTsAKkpDQpuYW1lc3BhY2UgQW5hbHlzaXPEd8ZMdW0gyy3EGCAgICB2MjogIjIuMSIsxxAzxBAwMjItMDgtMzEixBZ9y0NT5QCKSW5kZXhUeXBlVmFsdWXJTXRleHRFbGXlAYDHUHVuaWNvZGVDb2RlUOQAzMgXdGYxNsQVVW5pxhTHZUBhZGTuANfmAYDoATtNZXRob2QgdXNlZCB0byBjb21wdXRl5wEhIG9mZnNldOUCHmxlbmd0aOUCBiAgQGtub3du5gCtKPUAw8UnbW9kZWzwAOMgaXPHX%2BUCnCAgYWxpYXPpAWFD5gKbxCpzID3EICAgfCAiYXBwbGljYXRpb24vanNvbuUBSdEab2N0ZXQtc3RyZWFt1iJwZGbKGWltYWdlL2pwZWfQFHBu0RN0aWbRO2JtcNATaGVpZuYDougBY0TnA0MgYegCRHBhcmFtZXRlcuYDVugBKeUBA3plyDBSZXF1ZXN06AINz01VUkzkAbHFVHplxkcgIHVybFPlAvs%2F6wLlyj5CYXNlNjQgZW5jb2TmAeAgdGhl6QPl01FA5AONYXQoYnl05wHVICBixUbUaP8CdSAgQHJvdXRlKCIvyHNN5AD6cy975QECSWR9Ou0AgEBzdW1tYXJ5KCLnARzpAKvHIOUA1sccc8kdIHdpdGjKDsVc6AK6cG9zdMQJb3DoAOso5wDqaGVhZGVy6AUc5AKBOvUClugBUnBhdGjGXElk9QFuTGlzdOQBYzEt5AEyZCBwYWdlIG51bWJlcnPrAWsuICBFeC4gXCIxLTMsNSw3LTlcIukBf3BhdHRlcm4oIl4oXFxkKygtxAYpPykoLFxccyrOFCkqJMk4cXVlcnnFcnP2AJxvY2FsZSBoaW50IGZvcuUEayDnBXXkAynlA%2FTpAULoArouICDlA98gbWF55QEpYWluIG9ubHnlAkfkBqh15ADk5ASiIChl5QDVZW5cIiwgXCJmclwiKSBvciBCQ1AgNDfKLXRhZ8osLVVTXCIp5wGs6QDHbOUArfUAyP8EwPcEwMlaxijpBJw68AStyGxib2R5IMQFOiDlAwogfPcDrsQwKTogQWNjZXB0ZWRSZXNwb25zZTsgLy8gRklYTUUgTFJPDQp9)

**Comment by catalinaperalta** [comment]
I think I figured out what the problem was, will open again if not resolved.
