### ISSUE TITLE
Multiple @key on a model crashes the compiler

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#110]
```cadl
import "@cadl-lang/rest";
import "@cadl-lang/openapi3";

using Cadl.Rest;
using Cadl.Rest.Resource;

interface Pets mixes ResourceOperations<Pet, {}> {}

model Pet {
  @segment("stores")
  @key
  storeId: int64;

  @segment("pets")
  @key
  id: int64;
}
```

```
Unhandled promise rejection!
Internal compiler error!
File issue at https://github.com/microsoft/cadl

Error: More than one key found on model type Pet
    at file:///C:/dev/azsdk/cadl-dogfood/node_modules/@cadl-lang/rest/dist/resource.js:41:23
    at Map.forEach (<anonymous>)
    at getResourceTypeKey (file:///C:/dev/azsdk/cadl-dogfood/node_modules/@cadl-lang/rest/dist/resource.js:38:29)
    at cloneKeyProperties (file:///C:/dev/azsdk/cadl-dogfood/node_modules/@cadl-lang/rest/dist/resource.js:67:25)
    at $copyResourceKeyParameters (file:///C:/dev/azsdk/cadl-dogfood/node_modules/@cadl-lang/rest/dist/resource.js:108:9)
    at applyDecoratorToType (file:///C:/dev/azsdk/cadl-dogfood/node_modules/@cadl-lang/compiler/dist/core/checker.js:1268:13)
    at createType (file:///C:/dev/azsdk/cadl-dogfood/node_modules/@cadl-lang/compiler/dist/core/checker.js:1257:17)
    at checkModelStatement (file:///C:/dev/azsdk/cadl-dogfood/node_modules/@cadl-lang/compiler/dist/core/checker.js:819:13)
    at checkModel (file:///C:/dev/azsdk/cadl-dogfood/node_modules/@cadl-lang/compiler/dist/core/checker.js:762:20)
    at getTypeForNode (file:///C:/dev/azsdk/cadl-dogfood/node_modules/@cadl-lang/compiler/dist/core/checker.js:147:24)
```

not exactly sure if that's supposed to not be allowed but either way it shouldn't crash

**Comment by nguerrera** [comment]
Why does this trigger unhandled promise rejection?

**Comment by nguerrera** [comment]
That probably escapes the new catch-all in the language server.

**Comment by nguerrera** [comment]
Seems like there's a missing await somewhere too here?

**Comment by daviwil** [comment]
Side note: do we want to support multiple keys per model type?  We could get rid of the error entirely.

**Comment by timotheeguerin** [comment]
Someone was saying during the bug bash review that we were supposed to support that.

**Comment by bterlson** [comment]
It was me! I thought I saw it was required when my model has two keys, like a pet with a store ID and group ID or something. But I see now we just use the parent model relationship so I was mistaken.

**Comment by daviwil** [comment]
Honestly I don't see any reason why we couldn't use either approach.  The code I've written is only really concerned with the order of the keys, it could generate a path just fine for a model type with two or more key properties, even if it has multiple parents.

**Comment by bterlson** [comment]
I do think in practice it's common to have multiple foreign keys on an object, even when the entities they belong to themselves have a parent-child relationship. E.g. if kennel belongs to store and pet belongs to kennel, you will often find pets with both kennel_id and store_id, even though you can find the store_id through one indirection.

**Comment by markcowl** [comment]
- this issue is about fixing the excweption to make it a diagnostic
- Adding a design issue for whether multiple keys can be valid for a resource
