### ISSUE TITLE
Versioning a type using @autoRoute causes a compiler crash

### ISSUE THREAD

**Issue by markcowl** [microsoft/cadl#1298]
A simple type using autoRoute crashes the compiler when the entire type is versioned, for example:

``` cadl
enum Versions {
  "v1",
  "v2",
}

@added(Versions.v2)
model Widget {
  @key id: string;
  weight: int32;
  color: "red" | "blue";
  @added(Versions.v2) name: string;
}

@error
model Error {
  code: int32;
  message: string;
}

@added(Versions.v2)
interface WidgetService extends Resource.ResourceOperations<Widget, Error> {}
```

However, if you remove the decoration from the model, the interface is correctly removed from the early version, but the definition for Widget remains.

[Playground link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwrTGnZlcnNpb25pbmciOwoKdXNpbmcgQ2FkbC5WyRk7CgpAxydlZCjHGHMpCkBzZXJ2aWNlKHsKICB0aXRsZTogIldpZGdldCBTxhsiLAp9KQpuYW1lc3BhY2UgRGVtb8cbOwoKZW51bSDIUCDERiJ2MSIsxQgyxDvtAJFIdHRwO8wRUmVzdOQAnGFkZOsAmC52MikgCm1vZGVsIOcAjcRaQGtleSBpZDogc3Ry5QDUICB3ZWlnaHQ6IGludDMyxBFjb2xvcjogInJlZCIgfCAiYmx1ZSLEGeQAwco6fQoKQGVycm9yx2ZFxAzFZWNvZGXLUG1lc3NhZ8869ACuaW50ZXJm5AEh5gCy5wEjIGV4dGVuZHMgUmVzb3VyY2XkAPPFCU9wZXJhdMRBPMYyLOYAhj7mAOzSZMQWZ2V0xAdyb3V0ZSgiY3VzdG9tR2V0IsQdyQ4oKTrnAIXkAK8%3D)

Callstack from an ARM example  (this seems to apply to both key and segment decorators):

```
TypeError: Cannot read properties of undefined (reading 'forEach')
    at getResourceTypeKey (file:///C:/td/multiapi/node_modules/@cadl-lang/rest/dist/src/resource.js:19:29)
    at getResourceSegment (file:///C:/td/multiapi/node_modules/@cadl-lang/rest/dist/src/rest.js:101:25)
    at $segmentOf (file:///C:/td/multiapi/node_modules/@cadl-lang/rest/dist/src/rest.js:112:21)
    at applyDecoratorToType (file:///C:/td/multiapi/node_modules/@cadl-lang/compiler/dist/core/checker.js:3655:9)
    at finishTypeForProgramAndChecker (file:///C:/td/multiapi/node_modules/@cadl-lang/compiler/dist/core/checker.js:3635:13)
    at finishTypeForProgram (file:///C:/td/multiapi/node_modules/@cadl-lang/compiler/dist/core/checker.js:3626:12)
    at projectOperation (file:///C:/td/multiapi/node_modules/@cadl-lang/compiler/dist/core/projector.js:298:9)
    at projectType (file:///C:/td/multiapi/node_modules/@cadl-lang/compiler/dist/core/projector.js:84:29)
    at projectInterface (file:///C:/td/multiapi/node_modules/@cadl-lang/compiler/dist/core/projector.js:309:33)
    at projectType (file:///C:/td/multiapi/node_modules/@cadl-lang/compiler/dist/core/projector.js:87:29)
    at runEmitter (file:///C:/td/multiapi/node_modules/@cadl-lang/compiler/dist/core/program.js:493:19)
    at async compile (file:///C:/td/multiapi/node_modules/@cadl-lang/compiler/dist/core/program.js:230:9)
    at async Object.handler (file:///C:/td/multiapi/node_modules/@cadl-lang/compiler/dist/core/cli.js:109:25)
```

**Comment by timotheeguerin** [comment]
Simplying  the repro a little bit and removing the external interfaces 

https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwrTGnZlcnNpb25pbmciOwoKdXNpbmcgQ2FkbC5WyRk7zBdIdHRwzRFSZXN0OwoKQMdJZWQoxzpzKQpAc2VydmljZQpuYW1lc3BhY2UgRGVtb1PGFiB7CiAgZW51bSDIMsUSICAidjEiLMcKMsUKfQoKICBAYWRky18udjIpCiAgbW9kZWwgV2lkZ2V0x0BAa2V5IGlkOiBzdHLlAMDIQWVycm9yyTRFxA4ge9tcaW50ZXJm5AC3xmDoALlleHRlbmRzIExpYuQBAG91cmNlTGlzdDzGJz7oAIjVVSAgQHJvdXRlKCJjdXN0b21HZXQixhjJECgpOsdy5gC8fQrrAUJMaWLFYOoAne0Ag1TIDukApm9iamVj6gCVbGlzdHPIJSjJL%2BYAg8QdxH7JF1td6ACD

**Comment by timotheeguerin** [comment]
After a quick investigation I think this is the same problem as we had a while back with `@route` keeping index of removed operations. Here what happens when projecting to v1
```cadl

  @added(Versions.v2)
  interface WidgetService extends ResourceList<Widget> {}

  interface ResourceList<TResource extends object> {
    @listsResource(TResource)
    list(): TResource[];
  }

```
- project the interface widget service
- project all the operations in interface (`list`)
- run the decorators on the operation(in this case listOperations which allas segmentOf) passing Widget which is `never`
- **CRASH**
- **skip as it crashed** run the projection on the operation
- **skip as it crashed** run the projection on the interface(would have removed the operation)

cc: @bterlson

**Comment by markcowl** [comment]
Note that, in the original repro, this occurs irrespective of whether all of the references are versioned together.
