### ISSUE TITLE
Bug: Cannot use 'in' operator to search for 'file' in Symbol(NoTarget)

### ISSUE THREAD

**Issue by leni-msft** [microsoft/cadl#1299]
When `reportDiagnostic` on `NoTarget` in emitters, the Symbol is not equal to the one in core, causing the `if` check false:
https://github.com/microsoft/cadl/blob/1c08f74fddfde6e47f40008324ac0c588d5d36b6/packages/compiler/core/program.ts#L923

```
[{
	"resource": "/home/me/dogfooding/cadl-contoso/src/cadl/cadl/dbInsights.cadl",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Internal compiler error!\nFile issue at https://github.com/microsoft/cadl\n\nError: Emitter \"@azure-tools/cadl-autorest\" failed!\nFile issue at https://github.com/Azure/cadl-azure/issues\n\nTypeError: Cannot use 'in' operator to search for 'file' in Symbol(NoTarget)\n    at shouldSuppress (file:///home/me/workspace/cadl-azure/core/packages/compiler/dist/core/program.js:686:20)\n    at Object.reportDiagnostic (file:///home/me/workspace/cadl-azure/core/packages/compiler/dist/core/program.js:661:13)\n    at reportDiagnostic (file:///home/me/dogfooding/cadl-contoso/src/cadl/cadl/node_modules/@cadl-lang/compiler/dist/core/diagnostics.js:43:17)\n    at loadExamples (file:///home/me/dogfooding/cadl-contoso/src/cadl/cadl/node_modules/@azure-tools/cadl-autorest/dist/src/openapi.js:791:17)\n    at async emitOpenAPIFromVersion (file:///home/me/dogfooding/cadl-contoso/src/cadl/cadl/node_modules/@azure-tools/cadl-autorest/dist/src/openapi.js:189:13)\n    at async Object.emitOpenAPI (file:///home/me/dogfooding/cadl-contoso/src/cadl/cadl/node_modules/@azure-tools/cadl-autorest/dist/src/openapi.js:98:13)\n    at async Object.$onEmit [as emitFunction] (file:///home/me/dogfooding/cadl-contoso/src/cadl/cadl/node_modules/@azure-tools/cadl-autorest/dist/src/openapi.js:26:5)\n    at async runEmitter (file:///home/me/workspace/cadl-azure/core/packages/compiler/dist/core/program.js:476:13)\n    at async compile (file:///home/me/workspace/cadl-azure/core/packages/compiler/dist/core/program.js:230:9)\n    at async compile (file:///home/me/workspace/cadl-azure/core/packages/compiler/dist/server/serverlib.js:213:23)\n    at runEmitter (file:///home/me/workspace/cadl-azure/core/packages/compiler/dist/core/program.js:493:19)\n    at async compile (file:///home/me/workspace/cadl-azure/core/packages/compiler/dist/core/program.js:230:9)\n    at async compile (file:///home/me/workspace/cadl-azure/core/packages/compiler/dist/server/serverlib.js:213:23)\n    at async findDocumentHighlight (file:///home/me/workspace/cadl-azure/core/packages/compiler/dist/server/serverlib.js:334:9)",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}]
```

**Comment by timotheeguerin** [comment]
Should probably use `Symbol.For` as well here
