### ISSUE TITLE
OpenAPI emitters can't handle template pattern with recursion

### ISSUE THREAD

**Issue by nguerrera** [microsoft/cadl#133]
Compile this:
``` cadl
import "@cadl-lang/openapi3";
import "@cadl-lang/rest";

using Cadl.Http;

model ErrorTemplate<T> {
  @doc("Error code.") code: T;
  innererror?: InnerError;
}

model Error is ErrorTemplate<ErrorCode> {}
model InnerError is ErrorTemplate<InnerErrorCode> {}

enum ErrorCode {
  A,
  B,
  C
}

enum InnerErrorCode {
  C,
  D,
  E
}

@route("/")
namespace N {
  op M(): Error;
}
```

Get this:
```
TypeError: Cannot set properties of undefined (setting 'description')
    at getSchemaForModel (file:///C:/Temp/aqe/node_modules/@cadl-lang/openapi3/dist/src/openapi.js:811:58)
    at getSchemaForType (file:///C:/Temp/aqe/node_modules/@cadl-lang/openapi3/dist/src/openapi.js:661:20)
    at emitReferences (file:///C:/Temp/aqe/node_modules/@cadl-lang/openapi3/dist/src/openapi.js:625:35)
    at Object.emitOpenAPI (file:///C:/Temp/aqe/node_modules/@cadl-lang/openapi3/dist/src/openapi.js:157:13)
    at $onBuild (file:///C:/Temp/aqe/node_modules/@cadl-lang/openapi3/dist/src/openapi.js:11:19)
    at createProgram (file:///C:/Temp/aqe/node_modules/@cadl-lang/compiler/dist/core/program.js:60:19)
    at async compile (file:///C:/Temp/aqe/node_modules/@cadl-lang/compiler/dist/core/program.js:475:12)
    at async Object.handler (file:///C:/Temp/aqe/node_modules/@cadl-lang/compiler/dist/core/cli.js:67:25)
 ```
 
If you remove the `@doc("Error code") comment, it doesn't crash, but still gives this:
```
main.cadl:6:21 - error @cadl-lang/openapi3/invalid-schema: Couldn't get schema for type TemplateParameter
``` 

The behavior in both cases is the same for cadl-autorest as cadl-lang/openapi3 so we should fix both.

**Comment by timotheeguerin** [comment]
I can look at this one, remmeber I fixed the other cicular issues with template parameters must be another case to handle

**Comment by nguerrera** [comment]
@timotheeguerin Thanks! Probably worth looking at #134 at the same time.
