### ISSUE TITLE
@knownvalues can't be used with value definitions that are decorated with @added

### ISSUE THREAD

**Issue by sebastianrex** [microsoft/cadl#1332]
[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwrTGnZlcnNpb25pbmciOwoKdXNpbmcgQ2FkbC5WyRk7zBdIdHRwzRFSZXN0OwoKQMdJZWQoxzpzKQpAc2VydmljZSh7CiAgdGl0bGU6ICJXaWRnZXQgU8YbIiwKfSkKbmFtZXNwYWNlIERlbW%2FHGzsKCmVudW0gyFAgxEYidjEiLMUIMsQ7CgpAYWRky3UudjIpxjdFbnVtVmFsdWXHOUZvb8Y6QmFy2jttb2RlbCBNeU3FCMQ5QGtub3duxkooylUpCiAgZm9vOiBzdHJpbmcKfQ%3D%3D)

If you try to use `@knownvalues` with a value enum that's marked with `@added`, then you get an error, even if both the source and target were added in the same version.

The error you get is:

```
Internal Compiler error
File issue at https://github.com/microsoft/cadl
Error: Emitter "@cadl-lang/openapi3" failed! File issue at https://github.com/Microsoft/cadl/issues TypeError: Cannot read properties of undefined (reading 'values')
at $knownValues (https://cadlplayground.z22.web.core.windows.net/libs/@cadl-lang/compiler/index.js:9477:46)
at applyDecoratorToType (https://cadlplayground.z22.web.core.windows.net/libs/@cadl-lang/compiler/index.js:33977:9)
at finishTypeForProgramAndChecker (https://cadlplayground.z22.web.core.windows.net/libs/@cadl-lang/compiler/index.js:33957:13)
at finishTypeForProgram (https://cadlplayground.z22.web.core.windows.net/libs/@cadl-lang/compiler/index.js:33948:12)
at projectModelProperty (https://cadlplayground.z22.web.core.windows.net/libs/@cadl-lang/compiler/index.js:34439:13)
at projectModel (https://cadlplayground.z22.web.core.windows.net/libs/@cadl-lang/compiler/index.js:34366:35)
at projectType (https://cadlplayground.z22.web.core.windows.net/libs/@cadl-lang/compiler/index.js:34214:29)
at projectNamespaceContents (https://cadlplayground.z22.web.core.windows.net/libs/@cadl-lang/compiler/index.js:34303:31) at createProjector (https://cadlplayground.z22.web.core.windows.net/libs/@cadl-lang/compiler/index.js:34192:9)
at projectProgram (https://cadlplayground.z22.web.core.windows.net/libs/@cadl-lang/compiler/index.js:34783:12)
at runEmitter (https://cadlplayground.z22.web.core.windows.net/libs/@cadl-lang/compiler/index.js:35154:19)
at async Module.compile (https://cadlplayground.z22.web.core.windows.net/libs/@cadl-lang/compiler/index.js:34891:9)
at async S (https://cadlplayground.z22.web.core.windows.net/assets/index.4f9535d3.js:424:367)
```

**Comment by markcowl** [comment]
@markcowl associate with issue on decorator usage in removed types

**Comment by markcowl** [comment]
Closing as dupliacte of https://github.com/microsoft/cadl/issues/1298
