### ISSUE TITLE
Cadl compiler error  TypeError: location.file.getLineAndCharacterOfPosition is not a function

### ISSUE THREAD

**Issue by ruowan** [microsoft/cadl#1617]
Hi, I am running cadl compile with CADL APIView emitter. But I meet this issue. I am running cadl compile in this folder. https://github.com/Azure/azure-rest-api-specs-pr/tree/bdd5b2e22627657d2686b1321ae7fb181f0fe501/specification/pki/Microsoft.Pki

@tjprescott who committed on Cadl APIView project.

I am running cadl compile with these commands.
```
cd specification/pki/Microsoft.Pki
npm install 
npm install @azure-tools/cadl-apiview
npx cadl compile . --emit=@azure-tools/cadl-apiview --option @azure-tools/cadl-apiview.emitter-output-dir={projectRoot}/cadl-output
```

__Version info__
```
pki-cadl@ /home/ruowan/work/azure-rest-api-specs-pr/specification/pki/Microsoft.Pki
├── @azure-tools/cadl-apiview@0.3.4
├── @azure-tools/cadl-autorest@0.22.0
├── @azure-tools/cadl-azure-core@0.9.0
├── @cadl-lang/compiler@0.37.0
├── @cadl-lang/openapi3@0.17.0
└── @cadl-lang/rest@0.19.0
```
__Error log__
```
$ npx cadl compile . --emit=@azure-tools/cadl-apiview --option @azure-tools/cadl-apiview.emitter-output-dir={project-root}/cadl-output
Cadl compiler v0.37.0

Diagnostics were reported during compilation:

Internal compiler error!
File issue at https://github.com/microsoft/cadl

TypeError: location.file.getLineAndCharacterOfPosition is not a function
    at getLineAndColumn (file:///home/ruowan/work/azure-rest-api-specs-pr/specification/pki/Microsoft.Pki/node_modules/@cadl-lang/compiler/core/logger/console-sink.ts:92:29)
    at formatSourceLocation (file:///home/ruowan/work/azure-rest-api-specs-pr/specification/pki/Microsoft.Pki/node_modules/@cadl-lang/compiler/core/logger/console-sink.ts:53:21)
    at formatLog (file:///home/ruowan/work/azure-rest-api-specs-pr/specification/pki/Microsoft.Pki/node_modules/@cadl-lang/compiler/core/logger/console-sink.ts:29:31)
    at Object.log (file:///home/ruowan/work/azure-rest-api-specs-pr/specification/pki/Microsoft.Pki/node_modules/@cadl-lang/compiler/core/logger/console-sink.ts:15:17)
    at logDiagnostics (file:///home/ruowan/work/azure-rest-api-specs-pr/specification/pki/Microsoft.Pki/node_modules/@cadl-lang/compiler/core/diagnostics.ts:105:12)
    at onCompileFinished (file:///home/ruowan/work/azure-rest-api-specs-pr/specification/pki/Microsoft.Pki/node_modules/@cadl-lang/compiler/core/cli.ts:274:7)
    at Object.handler (file:///home/ruowan/work/azure-rest-api-specs-pr/specification/pki/Microsoft.Pki/node_modules/@cadl-lang/compiler/core/cli.ts:123:25)
```

**Comment by tjprescott** [comment]
This looks like a dependency mismatch.

Cadl APIView 0.3.4 requires version 0.39 of the cadl compiler. It is simply not compatible with 0.37, which is waht you are installing:
https://www.npmjs.com/package/@azure-tools/cadl-apiview?activeTab=explore

**Comment by tjprescott** [comment]
Please see: https://github.com/Azure/azure-sdk-tools/issues/5189
