### ISSUE TITLE
Passing union of string to @doc crash openapi emitter with circular reference in json

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#169]
```cadl
model Foo {
  @doc("foo" | "bar")
  test: string;
}
```
This happened when using wanting to use quotes but forgetting to escape and it happens to produce a valid Cadl syntax.

Error:
```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'options' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'Object'
    --- property 'parent' closes the circle
    at JSON.stringify (<anonymous>)
    at Object.emitOpenAPI (file:///C:/dev/azsdk/cadl-azure/packages/cadl-autorest/dist/src/openapi.js:172:100)
    at $onBuild (file:///C:/dev/azsdk/cadl-azure/packages/cadl-autorest/dist/src/openapi.js:13:19)
    at async createProgram (file:///C:/dev/azsdk/cadl-azure/core/packages/compiler/dist/core/program.js:60:13)
    at async compile (file:///C:/dev/azsdk/cadl-azure/core/packages/compiler/dist/core/program.js:479:12)
    at async Object.handler (file:///C:/dev/azsdk/cadl-azure/core/packages/compiler/dist/core/cli.js:67:25)
```

The problem with `@doc` specifically might just be to verify the value passed is a string and nothing else.

**Comment by markcowl** [comment]
- Should throw if first parameter is not a string
