### ISSUE TITLE
`using Cadl;` cause aggregate error

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#93]
Including `using Cadl;` in the spec cause an aggregate error 

```
AggregateError: Multiple errors. See errors array.
    at computeTargetLocation (file:///C:/dev/azsdk/cadl/packages/compiler/dist/core/diagnostics.js:73:15)
    at logDiagnostics (file:///C:/dev/azsdk/cadl/packages/compiler/dist/core/diagnostics.js:83:29)
    at onCompileFinished (file:///C:/dev/azsdk/cadl/packages/compiler/dist/core/cli.js:152:13)
    at async Object.handler (file:///C:/dev/azsdk/cadl/packages/compiler/dist/core/cli.js:67:25) {
  errors: [
    Error: Error(s) occurred trying to resolve target: [object Object]
        at computeTargetLocation (file:///C:/dev/azsdk/cadl/packages/compiler/dist/core/diagnostics.js:72:33)
        at logDiagnostics (file:///C:/dev/azsdk/cadl/packages/compiler/dist/core/diagnostics.js:83:29)
        at onCompileFinished (file:///C:/dev/azsdk/cadl/packages/compiler/dist/core/cli.js:152:13)
        at async Object.handler (file:///C:/dev/azsdk/cadl/packages/compiler/dist/core/cli.js:67:25),
    AssertionError [ERR_ASSERTION]: Cannot obtain source file of unbound node.
        at new AssertionError (internal/assert/assertion_error.js:456:5)
        at compilerAssert (file:///C:/dev/azsdk/cadl/packages/compiler/dist/core/diagnostics.js:221:19)
        at getSourceLocationOfNode (file:///C:/dev/azsdk/cadl/packages/compiler/dist/core/diagnostics.js:149:5)
        at getSourceLocation (file:///C:/dev/azsdk/cadl/packages/compiler/dist/core/diagnostics.js:135:12)
        at computeTargetLocation (file:///C:/dev/azsdk/cadl/packages/compiler/dist/core/diagnostics.js:64:24)
        at logDiagnostics (file:///C:/dev/azsdk/cadl/packages/compiler/dist/core/diagnostics.js:83:29)
        at onCompileFinished (file:///C:/dev/azsdk/cadl/packages/compiler/dist/core/cli.js:152:13)
        at async Object.handler (file:///C:/dev/azsdk/cadl/packages/compiler/dist/core/cli.js:67:25) {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: undefined,
      expected: undefined,
      operator: undefined
    }
  ]
}
```

**Comment by nguerrera** [comment]
Looking

**Comment by nguerrera** [comment]
This doesn't repro for me. There are no diagnostics for `using Cadl;` It is valid.

**Comment by nguerrera** [comment]
I take that back there are duplicate symbol diagnostics, but they don't cause the assertion for me. (On the side, this is related to #79, attributing the duplication to the definition instead of ambiguous references, means the errors just disappear in IDE because the library isn't open.)

**Comment by nguerrera** [comment]
I get this on cammand line.

```
C:\Users\nicholg\AppData\Roaming\npm\node_modules\@cadl-lang\compiler\dist\lib\decorators.js:1:1 - error duplicate-symbol: Duplicate name: "@doc"
```

It appears from this stack trace that the error is that computeTargetLocation doesn't come up with that location but instead throws in the repro case.

**Comment by nguerrera** [comment]
`import "@cadl-lang/rest"` is also required for the repro. This ends up reporting a diagnostic against a synthetic node for which we have no source location.
