### ISSUE TITLE
Playground not working in Firefox 103 (and possibly earlier versions)

### ISSUE THREAD

**Issue by daviwil** [microsoft/cadl#933]
I use Firefox primarily on Linux and I can never get the Playground page to load.  Since I saw #923 get fixed, I figured I should file an issue for this as well.

Here's the error that appears in the dev console when loading the page:

```
Uncaught TypeError: window.importShim is not a function
    YTe https://cadlplayground.z22.web.core.windows.net/prs/930/assets/index.1c91b14f.js:1132
    CSt https://cadlplayground.z22.web.core.windows.net/prs/930/assets/index.1c91b14f.js:1257
    <anonymous> https://cadlplayground.z22.web.core.windows.net/prs/930/assets/index.1c91b14f.js:1378
[index.1c91b14f.js:1132:11340](https://cadlplayground.z22.web.core.windows.net/prs/930/assets/index.1c91b14f.js)
    YTe https://cadlplayground.z22.web.core.windows.net/prs/930/assets/index.1c91b14f.js:1132
    CSt https://cadlplayground.z22.web.core.windows.net/prs/930/assets/index.1c91b14f.js:1257
    <anonymous> https://cadlplayground.z22.web.core.windows.net/prs/930/assets/index.1c91b14f.js:1378
    ExecuteAsyncModule self-hosted:2451
    InnerModuleEvaluation self-hosted:2361
    evaluation self-hosted:2322
```

This is after the fix for #923.

**Comment by bterlson** [comment]
Confirmed. It actually crashed my entire browser on windows...

**Comment by timotheeguerin** [comment]
Fun, seems to still be broken on safari. Believe the issue is the same neither firefox nor safari support importmap. (Firefox does behind a flag `dom.importMap.enabled` but safari not at all). Seems like my fix didn't work for the minified code

**Comment by ctaggart** [comment]
I see a similar errors on Edge.

```
cadlplayground.z22.web.core.windows.net/:16 

       GET https://cadlplayground.z22.web.core.windows.net/node_modules/es-module-shims/dist/es-module-shims.js net::ERR_ABORTED 404 (The requested content does not exist.)
index.9334b458.js:1132 
        
       Uncaught TypeError: window.importShim is not a function
    at YTe (index.9334b458.js:1132:11340)
    at CSt (index.9334b458.js:1257:451)
    at index.9334b458.js:1378:82988
YTe @ index.9334b458.js:1132
CSt @ index.9334b458.js:1257
(anonymous) @ index.9334b458.js:1378
```

**Comment by timotheeguerin** [comment]
I have a fix PR, the safari fix broke the published playground. With an import that work locally only
