### ISSUE TITLE
Some recursive type and decorator references negatively impact evaluation order

### ISSUE THREAD

**Issue by daviwil** [microsoft/cadl#960]
This issue is pretty weird.  A partner team has reported that a spec they authored fails compilation due to this internal error:

```
TypeError: Cannot read properties of undefined (reading 'keyProperty')
    at $parentResource (file:///home/daviwil/Projects/Code/cadl/fix-parent-resource/core/packages/rest/src/resource.ts:194:53)
    at applyDecoratorToType (file:///home/daviwil/Projects/Code/cadl/fix-parent-resource/core/packages/compiler/core/checker.ts:4337:5)
    at finishTypeForProgramAndChecker (file:///home/daviwil/Projects/Code/cadl/fix-parent-resource/core/packages/compiler/core/checker.ts:4312:7)
    at finishType (file:///home/daviwil/Projects/Code/cadl/fix-parent-resource/core/packages/compiler/core/checker.ts:2763:12)
    at checkModelStatement (file:///home/daviwil/Projects/Code/cadl/fix-parent-resource/core/packages/compiler/core/checker.ts:1985:7)
    at checkTypeReferenceSymbol (file:///home/daviwil/Projects/Code/cadl/fix-parent-resource/core/packages/compiler/core/checker.ts:898:17)
    at checkTypeReference (file:///home/daviwil/Projects/Code/cadl/fix-parent-resource/core/packages/compiler/core/checker.ts:759:18)
    at getTypeForNode (file:///home/daviwil/Projects/Code/cadl/fix-parent-resource/core/packages/compiler/core/checker.ts:499:16)
    at checkArrayExpression (file:///home/daviwil/Projects/Code/cadl/fix-parent-resource/core/packages/compiler/core/checker.ts:1153:25)
    at getTypeForNode (file:///home/daviwil/Projects/Code/cadl/fix-parent-resource/core/packages/compiler/core/checker.ts:493:16)
```

This happens because `parentResource` checks the parent resource type chain to see if any parent types have a conflicting key property name: https://github.com/microsoft/cadl/blob/main/packages/rest/src/resource.ts#L193

Under all normal circumstances, this works as expected.  The parent type's properties are evaluated before the child type, allowing the `parentResource` decorator to find the parent type's key property and successfully perform the comparison.

[This repro spec](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwoKQHNlcnZpY2VUaXRsZSgiV2lkZ2V0IFPGFSIpCm5hbWVzcGFjZSBEZW1vxxg7Cgp1c2luZyBDYWRsLkh0dHA7zBFSZXN0OwoKLy8gVGhpcyBpc3N1ZSBzb21laG93IHJlcXVpcmVzIHRocmVlIGZhY3RvcnMgdG8gYmUgaW4gcGxhY2U6xD0tIE1vcmUgdGhhbiBvbmUgcmVzb3VyY2UgdHlwZSBtdXN0IHNoYcUiZSBzYW1lIGBwYXJlbnRSxylgxkZUaGUgxhnUQ2JlIGJhc2VkIG9uIGEgdGVtcGxhdGVkxiJ3aGVyZSB5b3UgcGFzcyBhbm90aGVyIG1vZGVs5ADBb3VnaMtlcm9wZXJ0aeQA3cQ%2BdGhhdCBnZXRzxT7EVMYyxnloYXZlIGHINXnGLnJlZmXmAQ7kANUqc2Vjb25kKiBjaGls5gCT5QFXQ29tbWVudOQBcW91dCB05AFmxXJtYWvEfWhl5wF1Z28gYXdheQpA6AD5KCJwYXJ0cyIpCkDuASwo5gH6KQrmANzGDlBhcnQgewogIEBrZXkKIOQBRnRJZDogc3RyaW5nOwp9CsxabG9n31nJWUxvZ8xYbG9nz1fGLUJhc2XISDxUUOkBXz7FPeoBbzogyx3wAJd3xXLkAJrsAIIgaXPOX8YX0GTnAKHGRO8ApC8vIE5PVEU6IFB1dOUBjOQBeOsCBMcLeSBkaXJlY3RseeQCY8Qk5QGrYXZvaWTrAazET%2FUAti8v5wJw5wC5e8QS5wCaxQryAJ3FF%2BwBH%2FAA3cUj6QFn0B7lAPrpAN7kAtrmAk5yZXByb2R1Y2VzIHJlZ2FyZGxlc3Mgb2bkAyflAxjlAolsaW7EMSB1bmPmAqfkA1xyIG5vdOcCQuoAkGFydFtdOwrGbusELMtpd2hl5AE1aesBT2V4aXN0cyBidXQgZ29lc%2BUC4sYoaeUB13JlbW92ZWQu5gJZyW5Mb2fEbeQCHWVycm9y5wD9RcQM5QDyY29kZTogaW50MzI7CiAgbWVzc2FnZe0B82ludGVyZuQFDsZU5wUQIGV4dGVuZHMg6AJO5AUDxQlPcGVyYXRpb25z5wJhLMZx5wJe5AHQQHJvdXRlKCJjdXN0b21HZXQiKSDJDCgp6AC%2F5ACA) will cause the aforementioned error by ensuring that three factors are present:

- More than one resource type shares the same `parentResource`
- The parent resource type must be based on a templated type where you pass another model through
- The model type that gets passed through the template parameter must have a property that refers to the *second* child type

It seems that these factors affect evaluation order causing the `WidgetLog` type's properties to be evaluated before those of `Widget` causing `parentResource` to fail because `Widget`'s key property cannot be found.

**Comment by markcowl** [comment]
@daviwil Can we close this in favor of #967 ?

**Comment by markcowl** [comment]
Closinf for #967
